<script>
</script>
    

<h1>
Welcome
</h1>
<ul style="color: grey;">
    <li>
        <span class="inline-headline">
            Generation schemes:
        </span>
        Set how synthetic data should be generated by entering knowledge into forms
    <li>
        <span class="inline-headline">
            Jobs:
        </span>
        Start a process for generating synthetic data
</ul>


<style>
.inline-headline {
    font-weight: bold;
}
</style>



